version: '3'

services:
  web:
    platform: linux/amd64
    image: jbxonline/jbx-lamp:7.4
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/vhosts/laravel'
    networks:
      - network

  redis:
    image: 'redis'
    restart: always
    ports: ["6379"]
    networks:
      - network

networks:
  network:

